# Instructions
## Prerequisites
## 1. Prepare the data files.

The input file has to contain ID, sequence, and SNV information in separated columns by tab. The SNV information have to be provided as: wild-type nucleotide + position + mutant nucleotide.

Please refer to [Examples](Examples.md) for the detailed format.

## 2. Download and install necessary tools.
### a. Python (2.7.3)
Python can be downloaded from: https://www.python.org/downloads/
### b. RNAfold
RNAfold can be downloaded from: http://www.tbi.univie.ac.at/RNA/.
### c. RNAstructure
RNAstructure can be downloaded from: https://rna.urmc.rochester.edu/RNAstructure.html.
### d. Mfold(UNAfold)
UNAfold can be downloaded from: http://unafold.rna.albany.edu/?q=DINAMelt/software.

It will be perfect to make a-d all exceutable in your system. However, if you only want to use one of the three RNA folding algorithms (b to d), it is OK to install the target one, for example, RNAfold as recommended. Don't forget to specify your selected tool in Riprap program command line via -t option.


# Run Riprap
## 1. [Download the source code of Riprap.](Downloads.md) 
Riprap source code can be downloaded from the [Downloads](Downloads.md) page.
## 2. Check help page of Riprap for usage.
Riprap help page can be generated simply by typing:

Riprap_software_1.3.py -h

in your command window. And you should get the following lines:

[username]$ ./PRAS_1.0.py -h
![alt text](helppage.png)

If you get any errors in this command line, please go back to the prerequisites and check.

## 3. Collect Riprap output files.
In the running process of Riprap, it will generate some temporary folders and files. Therefore, please make sure you have the administrative rights of the system.
Riprap generated two folders named "seq" and "ppm", respectively.
The /seq/ folder contains the sequence file in the fasta format, called "wt_mut_allseq.fa", which is a fasta file that contains the wild-type and mutant sequences generated from the input file.
The /ppm/ folder contains the files generated by the RNA folding algorithm, which is selected by the user. For example, if "RNAfold" is chosen to be the folding algorithm, the /ppm/ folder will have files with the suffix "_dp.ps" and "_ss.ps" that are generated by RNAfold for the corresponding sequences in /seq/.
In addition, Riprap generated files with suffix ".ppm" from the output of the selected folding algorithm, which contain the base pairing probability matrix for the sequences.
The final ouput file of Riprap is with suffix "_riprap_score.tab" that contains the prediction results of the SNVs.

Please refer to [Examples](Examples.md) for the detailed output format of Riprap.
